### ISSUE TITLE
base91 test errors on pypy and pypy3

### ISSUE THREAD

**Issue by rossengeorgiev** [rossengeorgiev/aprs-python#12]
```
======================================================================
ERROR: test_stability (tests.test_base91.c_Both)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/rossengeorgiev/aprs-python/tests/test_base91.py", line 110, in test_stability
    result = base91.to_decimal(text)
  File "/home/travis/build/rossengeorgiev/aprs-python/aprslib/base91.py", line 37, in to_decimal
    raise ValueError("invalid character in sequence")
ValueError: invalid character in sequence

**Comment by rossengeorgiev** [comment]
Unable to reproduce in `pypy 4.0.1`. Possibly bug in older version. Travis is running `2.4`

**Comment by rossengeorgiev** [comment]
Managed to reproduce. Apparently, it won't round properly with `int`.
``` bash
$ pypy -c "from math import log; a = log(91**53) / log(91); print a, int(a)"
53.0 52

**Comment by rossengeorgiev** [comment]
Did not fix it on travis.
