### ISSUE TITLE
ValueError while parsing a MicE packet

### ISSUE THREAD

**Issue by rossengeorgiev** [rossengeorgiev/aprs-python#5]
```python
>>> aprslib.parse('HB9EMQ-3>4W1WQ2,WIDE1-1,WIDE2-1,qAR,HB9BHU-10:`}G-l \x1c!/`10-12/145.450MHz-FDMA/8-2-TDMA_%')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.cygwin-2.0.4-i686/egg/aprslib/parsing.py", line 179, in parse
  File "build/bdist.cygwin-2.0.4-i686/egg/aprslib/parsing.py", line 627, in _parse_mice
ValueError: invalid literal for int() with base 16: '10-1'
```

**Comment by rossengeorgiev** [comment]
The problem appears to be in the regex 

https://github.com/rossengeorgiev/aprs-python/blob/master/aprslib/parsing.py#L621
